/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gasstation_management.UI.MainContentPanels;
import gasstation_management.BUS.QuanLyQuyenTaiKhoan_BUS;
import gasstation_management.BUS.QuanLyQuyen_BUS;
import gasstation_management.BUS.TraCuuHoaDon_BUS;
import gasstation_management.BUS.QuanLyTaiKhoan_BUS;
import gasstation_management.DTO.HoaDon;
import gasstation_management.DTO.NhanVien;
import gasstation_management.DTO.Quyen;
import gasstation_management.DTO.QuyenTaiKhoan;
import gasstation_management.DTO.TaiKhoan;
import gasstation_management.DataTable;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JScrollPane;
import javax.swing.border.TitledBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.time.temporal.TemporalAccessor;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;
import gasstation_management.UI.MainContentPanels.DetailHoaDon;
import gasstation_management.XuatExcel;
import gasstation_management.BUS.ThongKeBaoCao_BUS;
/**
 *
 * @author Vuong
 */
public class ThongKeBaoCao extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeBaoCao
     */
    
    ThongKeBaoCao_BUS thongKeBaoCao_BUS = new ThongKeBaoCao_BUS();
    DataTable table = new DataTable();
    public ThongKeBaoCao() {
        initComponents();
        cbbHinhThuc.removeAllItems();
        cbbHinhThuc.addItem("Nhập vào");
        cbbHinhThuc.addItem("Bán ra ");
        table.setHeaders(new String[]{"STT","Mã sp", "Tên sp", "Mã Pn", "NCC","Số lượng","Giá Nhập","Thời Gian","Tổng tiền"});
        table.setSize(table.getPreferredSize());
        table.getTable().setAutoCreateRowSorter(true);


        setTableData();
        // Dòng này chỉnh tỉ lệ các cột
        table.setJTableColumnsWidth(table.getWidth(), new double[]{0.5,1,1,1,2,1,2,2,2});
        scrollTable.add(table);
    }
public void setTableData()
    {  
                table.clear();
    // Do something with sqldate
     ArrayList dataList = new ArrayList<>();

        if(cbbHinhThuc.getSelectedIndex()==0)
        {
            dataList = thongKeBaoCao_BUS.getThongkeNhapVao_BUS(cbbHinhThuc.getSelectedIndex(),txtTimKiem.getText(),dateStart.getDate(),dateEnd.getDate());
          for(int i=0;i<dataList.size();i++)
           { 
          table.addRow((Vector) dataList.get(i));
            }
        }
        if(cbbHinhThuc.getSelectedIndex()==1)
        {
            dataList = thongKeBaoCao_BUS.getThongkeBanRa_BUS(cbbHinhThuc.getSelectedIndex(),txtTimKiem.getText(),dateStart.getDate(),dateEnd.getDate());
          for(int i=0;i<dataList.size();i++)
           { 
          table.addRow((Vector) dataList.get(i));
            }
        }
//      for(int i=0;i<dataList.size();i++)
//      { 
//          table.addRow((Vector) dataList.get(i));
//      }
      }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbbHinhThuc = new javax.swing.JComboBox<>();
        dateStart = new com.toedter.calendar.JDateChooser();
        dateEnd = new com.toedter.calendar.JDateChooser();
        exportExcel = new javax.swing.JButton();
        btnThonKe = new javax.swing.JButton();
        scrollTable = new java.awt.ScrollPane();
        txtTimKiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        cbbHinhThuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbHinhThuc.setBorder(javax.swing.BorderFactory.createTitledBorder("Hình thức"));
        cbbHinhThuc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbHinhThucItemStateChanged(evt);
            }
        });

        dateStart.setBorder(javax.swing.BorderFactory.createTitledBorder("Từ ngày"));
        dateStart.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateStartPropertyChange(evt);
            }
        });

        dateEnd.setBorder(javax.swing.BorderFactory.createTitledBorder("Đến ngày"));
        dateEnd.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateEndPropertyChange(evt);
            }
        });

        exportExcel.setText("Xuất Excel");
        exportExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportExcelActionPerformed(evt);
            }
        });

        btnThonKe.setText("Thống kê");
        btnThonKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThonKeActionPerformed(evt);
            }
        });

        txtTimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder("Từ khóa tìm kiếm"));

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(cbbHinhThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateStart, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(dateEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exportExcel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThonKe)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(49, 49, 49))
            .addComponent(scrollTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbHinhThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dateStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(exportExcel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThonKe)
                    .addComponent(jButton1))
                .addGap(33, 33, 33)
                .addComponent(scrollTable, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exportExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportExcelActionPerformed

    private void dateStartPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateStartPropertyChange
        // TODO add your handling code here:
//        setTableData();
    }//GEN-LAST:event_dateStartPropertyChange

    private void dateEndPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateEndPropertyChange
        // TODO add your handling code here:
//                setTableData();

    }//GEN-LAST:event_dateEndPropertyChange

    private void cbbHinhThucItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbHinhThucItemStateChanged
        // TODO add your handling code here:
        
        if(cbbHinhThuc.getSelectedIndex()==0)
        {
                   table.setHeaders(new String[]{"STT","Mã sp", "Tên sp", "Mã Pn", "NCC","Số lượng","Giá Nhập","Thời Gian","Tổng tiền"});
                   table.setJTableColumnsWidth(table.getWidth(), new double[]{0.5,1,1,1,2,1,2,2,2});
                   table.getTable().setAutoCreateRowSorter(true);


        setTableData();

        }
        if(cbbHinhThuc.getSelectedIndex()==1)
        {
            table.setHeaders(new String[]{"STT","Mã sp", "Tên sp", "Mã HD","Số lượng","Giá bán","Thời Gian","Tổng tiền"});
            table.setJTableColumnsWidth(table.getWidth(), new double[]{0.5,1,1,1,2,1,2,2});
            table.getTable().setAutoCreateRowSorter(true);
       setTableData();
        }
            
    }//GEN-LAST:event_cbbHinhThucItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dateStart.setCalendar(null);
                dateEnd.setCalendar(null);
         txtTimKiem.setText("");
         setTableData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnThonKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThonKeActionPerformed
        // TODO add your handling code here:
        setTableData();
    }//GEN-LAST:event_btnThonKeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThonKe;
    private javax.swing.JComboBox<String> cbbHinhThuc;
    private com.toedter.calendar.JDateChooser dateEnd;
    private com.toedter.calendar.JDateChooser dateStart;
    private javax.swing.JButton exportExcel;
    private javax.swing.JButton jButton1;
    private java.awt.ScrollPane scrollTable;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
